language: ruby
bundler_args: --without development
script: "bundle exec rake validate && bundle exec rake lint && bundle exec rake spec SPEC_OPTS='--format documentation'"
before_install:
  - sudo apt-get install -qq augeas-tools augeas-lenses
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - 2.1.1
env:
  matrix:
  - PUPPET_GEM_VERSION="~> 2.6.0"
  - PUPPET_GEM_VERSION="~> 2.7.0"
  - PUPPET_GEM_VERSION="~> 3.0.0"
  - PUPPET_GEM_VERSION="~> 3.1.0"
  - PUPPET_GEM_VERSION="~> 3.2.0"
  - PUPPET_GEM_VERSION="~> 3.3.2"
  - PUPPET_GEM_VERSION="~> 3.4.3"
  - PUPPET_GEM_VERSION="~> 3.5.1"
matrix:
  fast_finish: true
  allow_failures:
    - env: PUPPET_GEM_VERSION="~> 2.6.0"
    - env: PUPPET_GEM_VERSION="~> 3.0.0"
    - env: PUPPET_GEM_VERSION="~> 3.1.0"
  exclude:
    - rvm: 1.9.3
      env: PUPPET_GEM_VERSION="~> 2.7.0"
    - rvm: 1.9.3
      env: PUPPET_GEM_VERSION="~> 2.6.0"
    - rvm: 2.0.0
      env: PUPPET_GEM_VERSION="~> 2.6.0"
    - rvm: 2.0.0
      env: PUPPET_GEM_VERSION="~> 2.7.0"
    - rvm: 2.0.0
      env: PUPPET_GEM_VERSION="~> 3.0.0"
    - rvm: 2.0.0
      env: PUPPET_GEM_VERSION="~> 3.1.0"
    - rvm: 2.1.1
      env: PUPPET_GEM_VERSION="~> 2.6.0"
    - rvm: 2.1.1
      env: PUPPET_GEM_VERSION="~> 2.7.0"
    - rvm: 2.1.1
      env: PUPPET_GEM_VERSION="~> 3.0.0"
    - rvm: 2.1.1
      env: PUPPET_GEM_VERSION="~> 3.1.0"
    - rvm: 2.1.1
      env: PUPPET_GEM_VERSION="~> 3.2.0"
    - rvm: 2.1.1
      env: PUPPET_GEM_VERSION="~> 3.3.2"
    - rvm: 2.1.1
      env: PUPPET_GEM_VERSION="~> 3.4.3"
notifications:
  email: false